node {	
	def MVN_HOME = tool 'maven-3.5.3';
	echo "MVN_HOME = ${MVN_HOME}"
	def JAVA_HOME = tool 'JDK7';
	echo "JAVA_HOME = ${JAVA_HOME}"
	def VERSION = "0.0.0-SNAPSHOT";
    parameters {
    string (
        defaultValue: '',
        description: '',
        name : 'VERSION_RELEASE	')
    string (
        defaultValue: '',
        description: '',
        name : 'VERSION_DEVELOPMENT')
    }
	stage("Parameters"){
		if (isUnix()) {
			sh  "echo VERSION_RELEASE : ${VERSION_RELEASE}"
			sh  "echo VERSION_DEVELOPMENT : ${VERSION_DEVELOPMENT}"
		} else {
			bat(/"echo VERSION_RELEASE : ${VERSION_RELEASE}"/)
			bat(/"echo VERSION_DEVELOPMENT : ${VERSION_DEVELOPMENT}"/)
		}
		if ("${params.VERSION_RELEASE}" == "" || "${params.VERSION_DEVELOPMENT}" == "") {
	        currentBuild.result = 'ABORTED'
	        error("Not valid values: VERSION_RELEASE(${VERSION_RELEASE}) | VERSION_DEVELOPMENT(${VERSION_DEVELOPMENT})")
		}
	}
	stage("Cleaning"){
	    cleanWs();
	}
	stage("Cheking out (GIT)") {
		checkout scm
	}
	stage("Update version (super-pom)") {
		if (isUnix()) {
			sh  "${MVN_HOME}/bin/mvn versions:set -DnewVersion=${VERSION} -f huhula-super-pom/pom.xml -Dmvn.antrun.config.skip.echoproperties=true -Dmvn.project.location=${WORKSPACE} "
		} else {
			bat(/"${MVN_HOME}\bin\mvn versions:set -DnewVersion=${VERSION} -f huhula-super-pom\pom.xml -Dmvn.antrun.config.skip.echoproperties=true -Dmvn.project.location=${WORKSPACE} "/)
		}
	}
	stage("Deploy (super-pom)") {
		if (isUnix()) {
			sh  "${MVN_HOME}/bin/mvn clean integration-test deploy site -f huhula-super-pom/pom.xml -Dmvn.antrun.config.skip.echoproperties=true -Dmvn.project.location=${WORKSPACE} "
		} else {
			bat(/"${MVN_HOME}\bin\mvn clean  integration-test deploy site -f huhula-super-pom\pom.xml -Dmvn.antrun.config.skip.echoproperties=true -Dmvn.project.location=${WORKSPACE} "/)
		}
	}
	stage("Deploy (parent-pom)") {
		if (isUnix()) {
			sh  "${MVN_HOME}/bin/mvn clean integration-test deploy site -Dmvn.antrun.config.skip.echoproperties=true -Dmvn.project.location=${WORKSPACE} "
		} else {
			bat(/"${MVN_HOME}\bin\mvn clean integration-test deploy site -Dmvn.antrun.config.skip.echoproperties=true -Dmvn.project.location=${WORKSPACE} "/)
		}
	}
	stage("Site ") {
		if (isUnix()) {
			sh "'${MVN_HOME}/bin/mvn' site -Dmvn.project.location=${WORKSPACE} -Dmvn.verify.fail=false "
		} else {
			bat(/"${MVN_HOME}\bin\mvn site -Dmvn.project.location=${WORKSPACE} -Dmvn.verify.fail=false "/)
		}
	}
	stage("revert version") {
		if (isUnix()) {
			sh "'${MVN_HOME}/bin/mvn' -f huhula-super-pom/pom.xml versions:revert -Dmvn.project.location=${WORKSPACE} -Dmvn.antrun.config.skip.echoproperties=true "
		} else {
			bat(/"${MVN_HOME}\bin\mvn -f huhula-super-pom\pom.xml versions:revert -Dmvn.project.location=${WORKSPACE} -Dmvn.antrun.config.skip.echoproperties=true "/)
		}		
	}
	stage("release - prepare (dry)") {
		if (isUnix()) {
			sh "'${MVN_HOME}/bin/mvn' release:clean release:prepare -Dresume=false -DdryRun=true --batch-mode -Dtag=${VERSION_RELEASE} -DreleaseVersion=${VERSION_RELEASE} -DdevelopmentVersion=${VERSION_DEVELOPMENT} -Dmvn.project.location=${WORKSPACE} -Dmvn.antrun.config.skip.echoproperties=true "
		} else {
			bat(/"${MVN_HOME}\bin\mvn release:clean release:prepare -Dresume=false -DdryRun=true --batch-mode -Dtag=${VERSION_RELEASE} -DreleaseVersion=${VERSION_RELEASE} -DdevelopmentVersion=${VERSION_DEVELOPMENT} -Dmvn.project.location=${WORKSPACE} -Dmvn.antrun.config.skip.echoproperties=true "/)
		}		
	}
	stage("release - revert") {
		if (isUnix()) {
			sh "'${MVN_HOME}/bin/mvn' release:rollback "
		} else {
			bat(/"${MVN_HOME}\bin\mvn release:rollback "/)
		}		
	}
	stage("release - prepare") {
		if (isUnix()) {
			sh "'${MVN_HOME}/bin/mvn' release:clean release:prepare -Dresume=false -DdryRun=false --batch-mode -Dtag=${VERSION_RELEASE} -DreleaseVersion=${VERSION_RELEASE} -DdevelopmentVersion=${VERSION_DEVELOPMENT} -Dmvn.project.location=${WORKSPACE} -Dmvn.antrun.config.skip.echoproperties=true "
		} else {
			bat(/"${MVN_HOME}\bin\mvn release:clean release:prepare -Dresume=false -DdryRun=false --batch-mode -Dtag=${VERSION_RELEASE} -DreleaseVersion=${VERSION_RELEASE} -DdevelopmentVersion=${VERSION_DEVELOPMENT} -Dmvn.project.location=${WORKSPACE} -Dmvn.antrun.config.skip.echoproperties=true "/)
		}		
	}
	stage("release - prepare") {
		if (isUnix()) {
			sh "'${MVN_HOME}/bin/mvn' release:clean "
		} else {
			bat(/"${MVN_HOME}\bin\mvn release:clean "/)
		}		
	}
}

